urls.py
from django.urls import path
from . import views

app_name = 'pdf_editor'

urlpatterns = [
#    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('upload/', views.UploadFile, name='UploadFile'),
    path('modify/', views.ChooseModifyFile, name='ChooseModifyFile'),
    path('download/', views.DownloadFile, name='DownloadFile'),
]

models.py
from django.db import models


# Create your models here.
class PdfEditorModel(models.Model):
    # fields of the model
    author = models.CharField(max_length=100, blank=True)
    title = models.CharField(max_length=200)
    description = models.TextField()
    file = models.FileField(upload_to='documents/', default='Choose a file')

    # renames the instances of the model
    # with their title name
    def __str__(self):
        return self.title

    @property
    def get_id(self):
        return self.id


class PdfChooseModifyModel(models.Model):
    # id = models.AutoField()
    PD_OPTION_01 = 'CP'
    PD_OPTION_02 = 'JE'
    PAGE_DUPLICATE_OPTION_CHOISES = [
        (PD_OPTION_01, 'Collate Pages'),
        (PD_OPTION_02, 'Join to End'),
    ]
    pages_to_duplicate = models.CharField(max_length=100)
    duplicate_copies = models.IntegerField(default=1)
    duplicate_option = models.CharField(max_length=2, choices=PAGE_DUPLICATE_OPTION_CHOISES, default=PD_OPTION_01)

    def __str__(self):
        return str(self.duplicate_option)

forms.py
import re
from django import forms
from PyPDF2 import PdfReader, PdfWriter
from .models import PdfEditorModel, PdfChooseModifyModel


class PdfEditorForm(forms.ModelForm):
    description = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 3}),
        required=False,
    )

    class Meta:
        model = PdfEditorModel
        fields = ['author', 'title', 'description', 'file']

    def clean_file(self):
        file = self.cleaned_data.get('file', False)
        try:
            filetype = file.content_type
        except:
            raise forms.ValidationError("'%s' is not a file." % file, code='invalid')
        else:
            if "pdf" not in filetype:
                raise forms.ValidationError("File '%s' is not pdf." % file)
        return file
    """
    def tmp_func(self):
        queryset = self.Meta.model._default_manager.get_queryset()
        for set in queryset:
            print(set.get_id)
        field = queryset.model._meta.pk
        print("%s / %s" % (field, self.__class__.__name__))
        print(self.fields)
    """


class PdfChooseModifyForm(forms.ModelForm):
    duplicate_copies = forms.IntegerField(
        label='Number of Copies:', initial=1,
        help_text='Input number between 1 and 1000',
        widget=forms.NumberInput(attrs={'min': 1, 'max': 1000}),
    )
    duplicate_option = forms.ChoiceField(
        label='Duplicate option:',
        help_text='1 1 1, 2 2 2 ... or 1 2 3, 1 2 3 ...',
        widget=forms.Select(),
        choices=PdfChooseModifyModel.PAGE_DUPLICATE_OPTION_CHOISES,
    )

    class Meta:
        model = PdfChooseModifyModel
        fields = ['pages_to_duplicate', 'duplicate_copies', 'duplicate_option']

    def clean_pages_to_duplicate(self):
        pages = self.cleaned_data.get('pages_to_duplicate', '1')
        invalid_symbols = re.findall('[^-,\s\d]', pages)
        if invalid_symbols != []:
            raise forms.ValidationError("Incorrect value. Use digits, coma(','), range separator('-') and space(' ')", code='invalid')
        return pages

    def clean_duplicate_copies(self):
        copies = int(self.cleaned_data.get('duplicate_copies', 0))
        if copies < 1:
            raise forms.ValidationError("Incorrect value", code='invalid')
        return copies

    def Modify_PDF_file(self, form_id):
        def get_filename(path):
            from pathlib import Path
            p = Path(path)
            return p.stem, p.parent

        def get_duplicate_pages_num(pages_count):
            pages_count = int(pages_count)
            dupl_pagesB: bool = [False for i in range(pages_count)]
            pages = self.data.get('pages_to_duplicate')
            pages = re.sub('[^-,\d]', '', pages).split(',')
            for pg in pages:
                r0 = re.split('-', pg)
                if len(r0) == 1: r0.append(r0[0])
                for i in range(0 if r0[0] == '' else int(r0[0]) - 1, pages_count if r0[1] == '' else int(r0[1])):
                    if i >= 0 and i < pages_count:
                        dupl_pagesB[i] = True
            return dupl_pagesB

        result = -1
        try:
            f1 = PdfEditorModel.objects.get(pk=form_id)
            existing_pdf = PdfReader(f1.file.path)
            pages_count = int(existing_pdf.numPages)
        except:
            result = 1
            return result, 'Undefined'
        new_pdf = PdfWriter()
        pages_to_duplicate = get_duplicate_pages_num(pages_count)
        copies = int(self.data.get('duplicate_copies', 0))
        duplicate_option = self.data.get('duplicate_option')
        from copy import copy
        if duplicate_option == PdfChooseModifyModel.PD_OPTION_01:
            for p in range(pages_count):
                for cp in range(1 + copies if pages_to_duplicate[p] else 1):
                    new_pdf.add_page(copy(existing_pdf.pages[p]))
        elif duplicate_option == PdfChooseModifyModel.PD_OPTION_02:
            #new_pdf.clone_document_from_reader(existing_pdf)
            for cp in range(1 + copies):
                for p in range(pages_count):
                    if cp == 0 or pages_to_duplicate[p]:
                        new_pdf.add_page(copy(existing_pdf.pages[p]))
        filename, dirname = get_filename(f1.file.path)
        newfile_fullpath = str(dirname)+"/"+filename+"-modify.pdf"
        with open(newfile_fullpath, "wb") as f:
            new_pdf.write(f)
        return result, newfile_fullpath

views.py
from django.shortcuts import (render, redirect, reverse)
from django.contrib import messages
from django.contrib.messages import get_messages
from django.http import HttpResponse #, HttpResponseRedirect

# Create your views here.
from .forms import PdfEditorForm, PdfChooseModifyForm


def index(request):
    # dictionary for initial data with
    # field names as keys
    context = {}

    # add the dictionary during initialization
    try:
        saved_form_id = int(request.session['uploaded_id'])
        download_filename = request.session['download_filename']
    except:
        pass
    else:
        context['download_filename'] = download_filename

    context['title'] = "PDF editor"
    return render(request, "pdf_editor/index.html", context)


def UploadFile(request):
    context = {'title': "Upload PDF file"}
    if request.method == 'POST':
        form = PdfEditorForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            request.session['uploaded_id'] = str(form.instance.id)
            messages.add_message(request, messages.SUCCESS, 'The file is saved')
            # return HttpResponse('The file is saved')
            return redirect(reverse('pdf_editor:ChooseModifyFile'))
    else:
        form = PdfEditorForm()
    context['form'] = form
    return render(request, 'pdf_editor/upload.html', context)


def ChooseModifyFile(request):
    context = {'title': "Choose modify PDF file"}
    if request.method == 'POST':
        form = PdfChooseModifyForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                saved_form_id = int(request.session['uploaded_id'])
            except:
                messages.add_message(request, messages.ERROR, "Unknown error: can't read session variable 'uploaded_id'.")
            else:
                result, new_filename = form.Modify_PDF_file(saved_form_id)
                if result < 0:
                    messages.add_message(request, messages.SUCCESS, 'The file modify is complete. Starting download...')
                    request.session['download_filename'] = new_filename
                else:
                    messages.add_message(request, messages.ERROR, "Unknown error: can't modify PDF file.")
            return redirect(reverse('pdf_editor:index'))
    else:
        form = PdfChooseModifyForm()
    context['form'] = form
    return render(request, 'pdf_editor/modify.html', context)


def DownloadFile(request):
    import os, mimetypes
    #filename = ''
    try:
        saved_form_id = int(request.session.pop('uploaded_id'))
        filename = request.session.pop('download_filename')
    except:
        pass
    else:
        if filename != '':
            path = open(filename, 'rb')
            mime_type, _ = mimetypes.guess_type(filename)
            response = HttpResponse(path, content_type=mime_type)
            response['Content-Disposition'] = "attachment; filename=%s" % os.path.basename(filename)
            return response
    return redirect(reverse('pdf_editor:index'))

templates/pdf_editor/base.html
{% load i18n static %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:'en-us' }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
<title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static 'pdf_editor/css/base.css' %}{% endblock %}">
</head>
<body>
<!-- Header -->
<div id="header">
<div id="branding">
<h1>PDF Editor page</h1>
</div>
<div id="user-tools">
Wellcome to PDF_editor page
</div>
</div>
<!-- END Header -->
    {% block breadcrumbs %}
    <div class="breadcrumbs">
    <a href="{% url 'home' %}">{% trans 'Home' %}</a>
    {% if title %} &rsaquo; {{ title }}{% endif %}
    </div>
    {% endblock %}

    <!-- Content -->
    <div id="content" class="{% block coltype %}colM{% endblock %}">
        {% block pretitle %}{% if messages %}
        <ul class="messagelist">{% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}</ul>
        {% endif %}{% endblock %}
        {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}
        {% block content %}
        {% block object-tools %}{% endblock %}
        {{ content }}
        {% endblock %}
        {% block sidebar %}{% endblock %}
        <br class="clear">
    </div>
    <!-- END Content -->

<!-- Footer -->
{% block footer %}<div id="footer"></div>{% endblock %}
<!-- END Footer -->
{% block download %}{% endblock %}
</body>
</html>

templates/pdf_editor/download.html
<iframe width="1" height="1" frameborder="0" src="/pdf/download"></iframe>

templates/pdf_editor/index.html
{% extends "pdf_editor/base.html" %}
{% load i18n static %}
{% block title %}PDF_editor page{% endblock %}
{% block content_title %}{% endblock %}
{% block content %}<h2>Hello world!</h2>
<a href="{% url 'pdf_editor:UploadFile' %}">{% trans 'Upload PDF file' %}</a>{% endblock %}
{% if download_filename %}{% block download %}{% include "pdf_editor/download.html" %}{% endblock %}{% endif %}

templates/pdf_editor/modify.html
{% extends "pdf_editor/base.html" %}
{% load i18n static %}
{% block title %}PDF modify options page{% endblock %}
{% block content %}
    <form method='post'>
        {% csrf_token %}
        <table>{{form.as_table}}</table>
        <input type="submit" value="Submit">
        <input type="button" value="Cancel" onclick="location.href='{% url 'pdf_editor:index' %}'">
    </form>
{% endblock %}

templates/pdf_editor/upload.html
{% extends "pdf_editor/base.html" %}
{% load i18n static %}
{% block title %}PDF file upload page{% endblock %}
{% block content %}
    <form method='post' enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit">
        <input type="button" value="Cancel" onclick="location.href='{% url 'pdf_editor:index' %}'">
    </form>
{% endblock %}